# Generated by Django 4.2.27 on 2025-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko')),
                ('address', models.CharField(max_length=512, verbose_name='Adres zamieszkania')),
                ('pesel', models.CharField(max_length=11, unique=True, verbose_name='Numer PESEL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Podpis zweryfikowany')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_pdfs/', verbose_name='Podpisany plik PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sygnatariusz',
                'verbose_name_plural': 'Sygnatariusze',
                'ordering': ['-created_at'],
            },
        ),
    ]
